package com.tigrinho.slot.model.entity;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;

import java.math.BigDecimal;

/**
 * Represents a player entity in the game, stored in MongoDB.
 * This class holds player-specific data including authentication details,
 * wallet balance, and Provably Fair seeds.
 */
@Data // Generates Getters, Setters, toString, equals, hashCode
@Builder // Builder pattern for easy object creation
@NoArgsConstructor // Default constructor (required by Spring Data)
@AllArgsConstructor // Constructor with all arguments (useful with Builder)
@Document(collection = "players") // Maps this class to the "players" collection in MongoDB
public class Player {

    /**
     * The unique identifier for the player, generated by MongoDB.
     */
    @Id
    private String id;

    /**
     * The player's username, which must be unique across all players.
     * Indexed for efficient lookup and uniqueness enforcement.
     */
    @Indexed(unique = true) // Ensures no two players have the same username
    private String username;

    /**
     * The hashed password of the player for secure authentication.
     */
    private String hashedPassword;

    /**
     * The current balance of the player's wallet.
     */
    private BigDecimal balance;

    /**
     * The secret server seed used in the Provably Fair system.
     * This is kept secret by the server.
     */
    private String serverSeed;

    /**
     * The hash of the server seed, provided to the player for verification.
     */
    private String serverSeedHash;

    /**
     * The client seed provided by the player for the Provably Fair system.
     */
    private String clientSeed;

    /**
     * A nonce (number used once) that increments with each game round
     * to ensure unique game outcomes for the Provably Fair system.
     */
    private Long nonce;
}
