package com.tigrinho.slot.mapper;

import com.tigrinho.slot.model.dto.request.CreatePlayerRequest;
import com.tigrinho.slot.model.dto.response.PlayerResponse;
import com.tigrinho.slot.model.entity.Player;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

/**
 * Mapper interface for converting between Player DTOs and entities.
 * This interface uses MapStruct to generate the implementation at compile time.
 */
@Mapper(componentModel = "spring")
public interface PlayerMapper {

    /**
     * Converts a {@link Player} entity to a {@link PlayerResponse} DTO.
     *
     * @param player The {@link Player} entity to convert.
     * @return The converted {@link PlayerResponse} DTO.
     */
    PlayerResponse toPlayerResponse(final Player player);

    /**
     * Converts a {@link CreatePlayerRequest} DTO to a {@link Player} entity.
     * Specific fields like 'id', 'balance', and 'hashedPassword' are ignored
     * as they are handled by the service layer or MongoDB.
     *
     * @param request The {@link CreatePlayerRequest} DTO to convert.
     * @return The converted {@link Player} entity.
     */
    @Mapping(target = "id", ignore = true) // ID will be generated by MongoDB
    @Mapping(target = "balance", ignore = true) // Initial balance will be set by the Service
    @Mapping(target = "hashedPassword", ignore = true) // Password will be encrypted by the Service
    Player toPlayer(final CreatePlayerRequest request);
}
